version: '3.8'

services:
  api:
    build: .
    container_name: arved-api
    ports:
      - '5001:5000'
    env_file:
      - .env
    working_dir: /app
    environment:
      - FLASK_APP=main.py
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
    command: >
      sh -c "./wait-for-it.sh db:3306 -- python main.py"

  db:
    image: mysql:8.0
    container_name: arved-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arved
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./uploads:/app/uploads

volumes:
  db_data:
